main = "dist/server/index.js"
assets = { directory = "dist/client" }
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "kv", id = "test-namespace" }
]
